#!/usr/bin/env bash
# PreToolUse hook (matcher: Write|Edit) — block writes to paths the agent shouldn't be editing.
#
# Targets the most common "agent overstep" cases: .git internals, vendored deps,
# build outputs, and the SOMI plugin install (so an agent doesn't rewrite its
# own ruleset under your feet).
#
# Lockfile writes are blocked by default (use `npm install <pkg>` etc instead),
# but a project can opt out via SOMI_ALLOW_LOCKFILES=1.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "$SCRIPT_DIR/../lib/common.sh"

somi::read_payload

TOOL="$(somi::field '.tool_name')"
PATH_INPUT="$(somi::field '.tool_input.file_path')"
[[ -z "$PATH_INPUT" ]] && exit 0

# Normalise relative paths so the leading-`*/` globs below still match
# (a relative `node_modules/x.js` would otherwise slip past `*/node_modules/*`).
# Same unexpanded-variable guard as common.sh's audit-log path.
if [[ "$PATH_INPUT" != /* ]]; then
  NORM_BASE="${CLAUDE_PROJECT_DIR:-$PWD}"
  [[ "$NORM_BASE" == *'${'* ]] && NORM_BASE="$PWD"
  PATH_INPUT="$NORM_BASE/$PATH_INPUT"
fi

PROTECTED_GLOBS=(
  # Source-control internals.
  '*/.git/*'

  # SOMI plugin install — never let an agent rewrite the ruleset under itself.
  '*/.claude/plugins/somi/*'

  # Vendored deps & build outputs.
  '*/node_modules/*'
  '*/vendor/*'
  '*/dist/*'
  '*/build/*'
  '*/target/*'
  '*/.next/*'
  '*/.nuxt/*'
  '*/__pycache__/*'
)

LOCKFILES=(
  'package-lock.json'
  'yarn.lock'
  'pnpm-lock.yaml'
  'Cargo.lock'
  'Gemfile.lock'
  'poetry.lock'
  'uv.lock'
  'composer.lock'
  'go.sum'
)

# Protected glob match (uses bash extglob).
shopt -s extglob
for glob in "${PROTECTED_GLOBS[@]}"; do
  # shellcheck disable=SC2053
  if [[ "$PATH_INPUT" == $glob ]]; then
    somi::deny_pretool "somi refused to ${TOOL} \`${PATH_INPUT}\`: this path matches a protected glob (\`${glob}\`).
These paths are owned by tooling (git / package managers / SOMI itself); changes belong in their respective workflows."
  fi
done

# Lockfile gate. Precedence: env (session override, even "0") > .somi/config.json
# (`lockfiles.allow_edit`, committed project policy) > default (deny).
ALLOW_LOCKFILES="${SOMI_ALLOW_LOCKFILES:-}"
if [[ -z "$ALLOW_LOCKFILES" && "$(somi::config '.lockfiles.allow_edit')" == "true" ]]; then
  ALLOW_LOCKFILES="1"
fi
if [[ "$ALLOW_LOCKFILES" != "1" ]]; then
  BASENAME="$(basename "$PATH_INPUT")"
  for lock in "${LOCKFILES[@]}"; do
    if [[ "$BASENAME" == "$lock" ]]; then
      somi::deny_pretool "somi refused to ${TOOL} \`${PATH_INPUT}\`: lockfiles should be regenerated by the package manager, not hand-edited.
If you genuinely need to hand-edit this lockfile, set SOMI_ALLOW_LOCKFILES=1 in your environment
for this session (or set \`lockfiles.allow_edit: true\` in \`.somi/config.json\` as project policy)."
    fi
  done
fi

exit 0
